import {
  CameraCore,
  CAMERA_MAKER,
  // OPTICS_TYPE,
  // SENSOR_TYPE,
  // SENSOR_SIZE,
  // FOCUS_NAME,
  // VIDEO_SCAN_TYPE,
  // ENGINE_TYPE,
  MOUNT,
  GRADE,
} from '@/types/cameras.d';

// https://en.wikipedia.org/wiki/Template:Olympus_DSLR_cameras
// https://en.wikipedia.org/wiki/Template:Micro_Four_Thirds_cameras

export const OLYMPUSES: CameraCore[] = [
  // 1995 =============================================
  // 1996 =============================================
  // 1997 =============================================
  // 1998 =============================================
  // 1999 =============================================
  // 2000 =============================================
  // 2001 =============================================
  // 2002 =============================================
  // 2003 =============================================
  {
    year: 2003,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.FourThird,
    grade: GRADE.FLAGSHIP,
    name: 'E-1',
    successor: 'E-3',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2004 =============================================
  {
    year: 2004,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.FourThird,
    grade: GRADE.ENTRY,
    name: 'E-300',
    successor: 'E-330',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2005 =============================================
  {
    year: 2005,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.FourThird,
    grade: GRADE.MIDRANGE,
    name: 'E-500',
    predecessor: 'E-510',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2006 =============================================
  {
    year: 2006,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.FourThird,
    grade: GRADE.ENTRY,
    name: 'E-330',
    predecessor: 'E-300',
    successor: 'E-450',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2006,
    maker: CAMERA_MAKER.OLYMPUS,
    name: 'E-400',
    mount: MOUNT.FourThird,
    grade: GRADE.ENTRY,
    successor: 'E-410',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2007 =============================================
  {
    year: 2007,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.FourThird,
    grade: GRADE.FLAGSHIP,
    name: 'E-3',
    predecessor: 'E-1',
    successor: 'E-5',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2007,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.FourThird,
    grade: GRADE.MIDRANGE,
    name: 'E-510',
    predecessor: 'E-500',
    successor: 'E-520',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2007,
    maker: CAMERA_MAKER.OLYMPUS,
    name: 'E-410',
    mount: MOUNT.FourThird,
    grade: GRADE.ENTRY,
    predecessor: 'E-400',
    successor: 'E-420',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2008 =============================================
  {
    year: 2008,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.FourThird,
    grade: GRADE.ADVANCED,
    name: 'E-30',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2008,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.FourThird,
    grade: GRADE.MIDRANGE,
    name: 'E-520',
    predecessor: 'E-510',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2008,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.FourThird,
    grade: GRADE.ENTRY,
    name: 'E-420',
    predecessor: 'E-410',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2009 =============================================
  {
    year: 2009,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.FourThird,
    grade: GRADE.MIDRANGE,
    name: 'E-620',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2009,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.FourThird,
    grade: GRADE.MIDRANGE,
    name: 'E-600',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2009,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.FourThird,
    grade: GRADE.ENTRY,
    name: 'E-450',
    predecessor: 'E-330',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2009,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'E-P1',
    successor: 'E-P2',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2009,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'E-P2',
    predecessor: 'E-P2',
    successor: 'E-P3',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2010 =============================================
  {
    year: 2010,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.FourThird,
    grade: GRADE.FLAGSHIP,
    name: 'E-5',
    predecessor: 'E-3',
    successor: 'E-M1X',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2010,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRYMID,
    name: 'E-PL1',
    successor: 'E-PL2',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2011 =============================================
  {
    year: 2011,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'E-P3',
    predecessor: 'E-P2',
    successor: 'E-P5',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2011,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRYMID,
    name: 'E-PL2',
    predecessor: 'E-PL1',
    successor: 'E-PL3',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2011,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRYMID,
    name: 'E-PL3',
    predecessor: 'E-PL2',
    successor: 'E-PL5',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2011,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRY,
    name: 'E-PM1',
    successor: 'E-PM2',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2012 =============================================
  {
    year: 2012,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.ADVANCED,
    name: 'E-M5',
    successor: 'E-M5 II',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2012,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRYMID,
    name: 'E-PL5',
    predecessor: 'E-PL3',
    successor: 'E-PL6',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2012,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRY,
    name: 'E-PM2',
    predecessor: 'E-PM1',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2013 =============================================
  {
    year: 2013,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.PROFESSIONAL,
    name: 'E-M1',
    successor: 'E-M1 II',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2013,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'E-P5',
    predecessor: 'E-P3',
    successor: 'PEN-F',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2013,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRYMID,
    name: 'E-PL6',
    predecessor: 'E-PL5',
    successor: 'E-PL7',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2014 =============================================
  {
    year: 2014,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'E-M10',
    successor: 'E-M10 II',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2014,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRYMID,
    name: 'E-PL7',
    predecessor: 'E-PL6',
    successor: 'E-PL8',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2015 =============================================
  {
    year: 2015,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.ADVANCED,
    name: 'E-M5 II',
    predecessor: 'E-M5',
    successor: 'E-M5 III',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2015,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'E-M10 II',
    predecessor: 'E-M10',
    successor: 'E-M10 III',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2016 =============================================
  {
    year: 2016,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.PROFESSIONAL,
    name: 'E-M1 II',
    predecessor: 'E-M1',
    successor: 'E-M1 III',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2016,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'PEN-F',
    predecessor: 'E-P5',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2016,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRYMID,
    name: 'E-PL8',
    predecessor: 'E-PL7',
    successor: 'E-PL9',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2017 =============================================
  {
    year: 2017,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'E-M10 III',
    predecessor: 'E-M10 II',
    successor: 'E-M10 IIIs',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2018 =============================================
  {
    year: 2018,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRYMID,
    name: 'E-PL9',
    predecessor: 'E-PL8',
    successor: 'E-PL10',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2019 =============================================
  {
    year: 2019,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.FLAGSHIP,
    name: 'E-M1X',
    predecessor: 'E-5',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2019,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.ADVANCED,
    name: 'E-M5 III',
    predecessor: 'E-M5 II',
    successor: 'OM-5',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2019,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRYMID,
    name: 'E-PL10',
    predecessor: 'E-PL9',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2020 =============================================
  {
    year: 2020,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.PROFESSIONAL,
    name: 'E-M1 III',
    predecessor: 'E-M1 II',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2017,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'E-M10 IIIs',
    predecessor: 'E-M10 III',
    successor: 'E-M10 IV',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
    refs: 'https://www.dpreview.com/products/olympus/slrs/olympus_em10iiis',
  },
  {
    year: 2020,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'E-M10 IV',
    predecessor: 'E-M10 III',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2021 =============================================
  {
    year: 2021,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'E-P7',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2022 =============================================
  {
    year: 2022,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.FLAGSHIP,
    name: 'OM-1',
    predecessor: 'E-M1X',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2022,
    maker: CAMERA_MAKER.OLYMPUS,
    mount: MOUNT.MFourThird,
    grade: GRADE.ADVANCED,
    name: 'OM-5',
    predecessor: 'E-M5 III',
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2023 =============================================
];
