import { ENGINE_TYPE, FOCUS_NAME, OPTICS_TYPE } from '@/types/cameras.d';
import { PENTAX_DSLR_MATERIAL, PENTAX_DSLR_SENSOR_SIZE, PENTAX_DSLR_TYPE, PentaxDslr } from '@/types/pentaxes.d';

export const PENTAX_DSLRS: PentaxDslr[] = [
  // Line 1 ==============================
  {
    type: PENTAX_DSLR_TYPE.K645,
    name: '645D',
    line: 1,
    startYear: 2010,
    startQuarter: 2,
    endYear: 2014,
    endQuarter: 1,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronMag,
        width: 156,
        height: 117,
        depth: 119,
        weight: '1400g, 배터리, SD카드 2장 포함 1480g',
      },
      mount: 'Pentax 645AF2, 645AF, 645A',
      power: 'D-LI90 리튬이온, AC전원',
      memory: 'SD, SDHC 2장',
      etc: '다중노출, 회전센서',
      comment:
        '여러 해 동안 출시 예고와 연기를 반복하던 펜탁스의 중형 포멧 DSLR이 드디어 출시되었다. 1000만원 이하의 놀라운 가격에 4000만화소 코닥 CCD 센서를 탑재하고, 방진방습과 초음파 먼지제거까지 달고 나온 엄청난 제품.',
      bonus: {
        wr: true,
        dustRemove: '초음파, 먼지경고',
      },
      sensor: {
        pixels: '4000만화소 CCD',
        size: PENTAX_DSLR_SENSOR_SIZE.C645,
        iso: 'ISO200-1000(100-1600)',
        engine: ENGINE_TYPE.PRIME2,
      },
      display: '92만 1000화소, 3.0인치 TFT LCD',
      imageType: 'RAW(12-bit PEF/DNG), JPEG',
      modes: 'P, M, Av, Tv, TAv, Sv, B, X, USER',
      meteringA: '77분할, 중앙중점, 스팟',
      meteringRange: '2 ~ 21ev',
      exposureRange: '±5ev',
      shutter: '30-1/4000sec, B',
      continuous: '1.1fps',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_PRISM,
        coverage: '98%',
        magnification: '0.62x (DFA55), 0.85x (FA75)x',
      },
      flash: {
        interlock: '디지털, X-Sync',
        modes: 'W, HS, P-TTL',
        syncSpeed: '30 ~ 1/125sec, B',
        redEye: true,
      },
      focus: {
        name: FOCUS_NAME.SAFOX9P,
        points: '11포인트',
        superImpose: true,
        supersonicMotor: true,
      },
    },
  },
  {
    type: PENTAX_DSLR_TYPE.K645,
    name: '645Z',
    line: 1,
    startYear: 2014,
    startQuarter: 2,
    data: {},
  },
  // Line 2 ==============================
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-1',
    line: 2,
    startYear: 2016,
    startQuarter: 2,
    endYear: 2018,
    endQuarter: 1,
    data: {},
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-1 II',
    line: 2,
    startYear: 2018,
    startQuarter: 2,
    data: {},
  },
  // Line 3 / 4 ==============================
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-3',
    line: 4,
    startYear: 2013,
    startQuarter: 4,
    endYear: 2016,
    endQuarter: 4,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronMag,
        width: 131.5,
        height: 100,
        depth: 77.5,
        weight: '720g, 배터리 포함 800g',
        verticalGrip: 'D-BG4',
      },
      mount: 'KAF3',
      power: 'D-LI90P 리튬이온, AC전원',
      memory: 'SD, SDHC, SDXC',
      etc: '다중노출, 회전센서',
      comment: '기존 K-5에서 AF 센서가 저광량 성능이 올라간 SAFOX X로 대폭 업그레이드 되었다.',
      bonus: {
        wr: true,
        sr: 'SR II, 4스탑',
        dustRemove: '초음파, SP코팅, 먼지경고',
      },
      sensor: {
        pixels: '2435만화소 CMOS',
        size: PENTAX_DSLR_SENSOR_SIZE.C1534,
        iso: 'ISO100-51200',
        engine: ENGINE_TYPE.PRIME2,
      },
      display: '104만화소, 3.2인치 TFT LCD',
      liveView: true,
      liveViewAF: '컨트라스트, 얼굴인식, 위상차',
      movie: '1920x1080i, 60fps',
      movieType: 'H.264',
      imageType: 'RAW(12-bit PEF/DNG), JPEG',
      modes: 'P, Sv, Tv, TAv, M, B, X, U1, U2, Green',
      meteringK: '중앙중점, 스팟',
      meteringA: '8.6메가픽셀 RGB, 중앙중점, 스팟',
      meteringRange: '0 ~ 22ev',
      exposureRange: '±5ev',
      shutter: '30-1/8000sec, B',
      continuous: '8.3fps에서 JPEG 40장, RAW 15장',
      continuousLength: '3.3fps에서 JPEG 무한, RAW 17장',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_PRISM,
        coverage: '100%',
        magnification: '0.95x',
        screenReplace: true,
      },
      flash: {
        interlock: '디지털',
        modes: 'HS, P-TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn13, 28mm',
        redEye: true,
        release: '케이블릴리즈 CS205',
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX11,
        points: '27포인트 25크로스',
        sensitivity: '-3 ~ 18ev',
        superImpose: true,
        supersonicMotor: true,
      },
      refs: 'https://m.popco.net/reviewView.php?IDX=899&BID=dica_review&SUB_CAT=1, https://www.popco.net/zboard/view.php?id=dica_brandlist&page=1&sn1=&divpage=1&category=14&sn=off&ss=on&sc=on&select_arrange=headnum&desc=asc&no=2028&category=14&category_name=%C6%E6%C5%B9%BD%BA%27#specfication',
    },
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-3 II',
    line: 3,
    startYear: 2015,
    startQuarter: 3,
    endYear: 2018,
    endQuarter: 1,
    data: {},
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-3 III',
    line: 3,
    startYear: 2021,
    startQuarter: 2,
    data: {},
  },
  // Line 5 ==============================
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-7',
    line: 5,
    startYear: 2009,
    startQuarter: 2,
    endYear: 2010,
    endQuarter: 3,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronMag,
        width: 131,
        height: 97,
        depth: 73,
        weight: '670g, 배터리 포함 750g',
        verticalGrip: 'D-BG4',
      },
      mount: 'KAF3',
      power: 'D-LI90 리튬이온, AC전원',
      memory: 'SD, SDHC',
      etc: '다중노출, 회전센서',
      comment:
        '타사 대비 성능상 많이 뒤쳐져 있었던 펜탁스 회심의 작품. 아쉬웠던 1/8000sec 셔터속도 지원, 초당 5연사, AF 등이 함께 개선. 동시에 동영상 촬영 기능도 최초로 들어갔다. 영하 10도까지 보장하는 강력한 방진방습 성능, 마그네슘 합금 바디, 이 모든 것을 합친 것이 타사 보급기 정도 사이즈로 나온 대단한 제품. 하지만 노이즈 등 화질이 기존 K20D에 못미친다는 평이 있고, 뒤에 나온 보급기인 K-x의 화질이 아주 뛰어나 비교되는 면이 있다. 2010년 2월에 실버 한정판이 나왔다.',
      bonus: {
        wr: true,
        sr: 'SR II, 4스탑',
        dustRemove: '초음파, SP코팅, 먼지경고',
      },
      sensor: {
        pixels: '1460만화소 CMOS',
        size: PENTAX_DSLR_SENSOR_SIZE.C1532,
        iso: 'ISO100-3200(6400)',
        engine: ENGINE_TYPE.PRIME2,
      },
      display: '92만 1000화소, 3.0인치 TFT LCD',
      liveView: true,
      liveViewAF: '컨트라스트, 얼굴인식, 위상차',
      movie: '1280x720p, 24fps',
      movieType: 'M-JPEG',
      imageType: 'RAW(12-bit PEF/DNG), JPEG',
      modes: 'M, B, P, Tv, Av, TAv, Sv, USER, Green, X, Movie',
      meteringK: '중앙중점, 스팟',
      meteringA: '77분할, 중앙중점, 스팟',
      meteringRange: '0 ~ 22ev',
      exposureRange: '±5ev',
      shutter: '30-1/8000sec, B',
      continuous: '5.2fps에서 JPEG 40장, PEF 15장, DNG 14장',
      continuousLength: '3.3fps에서 JPEG 무한, PEF 17장, DNG 17장',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_PRISM,
        coverage: '100%',
        magnification: '0.92x',
      },
      flash: {
        interlock: '디지털',
        modes: 'W, HS, P-TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn13, 28mm',
        redEye: true,
        release: '케이블릴리즈 CS205',
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX7P,
        points: '11포인트',
        sensitivity: '-1 ~ 18ev',
        superImpose: true,
        supersonicMotor: true,
      },
    },
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-5',
    line: 5,
    startYear: 2010,
    startQuarter: 4,
    endYear: 2012,
    endQuarter: 2,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronMag,
        width: 131,
        height: 97,
        depth: 73,
        weight: '670g, 배터리 포함 750g',
        verticalGrip: 'D-BG4',
      },
      mount: 'KAF3',
      power: 'D-LI90 리튬이온, AC전원',
      memory: 'SD, SDHC',
      etc: '다중노출, 회전센서',
      comment: '도움이 필요함',
      bonus: {
        wr: true,
        sr: 'SR II, 4스탑',
        dustRemove: '초음파, SP코팅, 먼지경고',
      },
      sensor: {
        pixels: '1630만화소 CMOS',
        size: PENTAX_DSLR_SENSOR_SIZE.C1532,
        iso: 'ISO100-12800(51200)',
        engine: ENGINE_TYPE.PRIME2,
      },
      display: '92만 1000화소, 3.0인치 TFT LCD',
      liveView: true,
      liveViewAF: '컨트라스트, 얼굴인식, 위상차',
      movie: '1920x1080p, 25fps',
      movieType: 'M-JPEG',
      imageType: 'RAW(12-bit PEF/DNG), JPEG',
      modes: 'M, B, P, Tv, Av, TAv, Sv, USER, Green, X, Movie',
      meteringK: '중앙중점, 스팟',
      meteringA: '77분할, 중앙중점, 스팟',
      meteringRange: '0 ~ 22ev',
      exposureRange: '±5ev',
      shutter: '30-1/8000sec, B',
      continuous: '7fps에서 JPEG 40장, RAW 15장',
      continuousLength: '3.3fps에서 JPEG 무한, RAW 17장',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_PRISM,
        coverage: '100%',
        magnification: '0.92x',
      },
      flash: {
        interlock: '디지털',
        modes: 'HS, P-TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn13, 28mm',
        redEye: true,
        release: '케이블릴리즈 CS205',
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX9P,
        points: '11포인트',
        sensitivity: '-1 ~ 18ev',
        superImpose: true,
        supersonicMotor: true,
      },
      refs: 'https://www.dpreview.com/reviews/pentaxk5/2',
    },
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-5 II / K-5 IIs',
    line: 5,
    startYear: 2012,
    startQuarter: 3,
    endYear: 2014,
    endQuarter: 4,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronMag,
        width: 131,
        height: 97,
        depth: 73,
        weight: '680g, 배터리 포함 760g',
        verticalGrip: 'D-BG4',
      },
      mount: 'KAF3',
      power: 'D-LI90P 리튬이온, AC전원',
      memory: 'SD, SDHC',
      etc: '다중노출, 회전센서',
      comment: '기존 K-5에서 AF 센서가 저광량 성능이 올라간 SAFOX X로 대폭 업그레이드 되었다.',
      bonus: {
        wr: true,
        sr: 'SR II, 4스탑',
        dustRemove: '초음파, SP코팅, 먼지경고',
      },
      sensor: {
        pixels: '1690만화소 CMOS',
        size: PENTAX_DSLR_SENSOR_SIZE.C1535,
        iso: 'ISO100-12800(80-51200)',
        engine: ENGINE_TYPE.PRIME2,
      },
      display: '92만 1000화소, 3.0인치 TFT LCD',
      liveView: true,
      liveViewAF: '컨트라스트, 얼굴인식, 위상차',
      movie: '1920x1080p, 25fps',
      movieType: 'M-JPEG',
      imageType: 'RAW(12-bit PEF/DNG), JPEG',
      modes: 'Av, HyM, HyP, P, Green, Sv, TAv, Tv',
      meteringK: '중앙중점, 스팟',
      meteringA: '77분할, 중앙중점, 스팟',
      meteringRange: '0 ~ 22ev',
      exposureRange: '±5ev',
      shutter: '30-1/8000sec, B',
      continuous: '7fps에서 JPEG 40장, RAW 15장',
      continuousLength: '3.3fps에서 JPEG 무한, RAW 17장',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_PRISM,
        coverage: '100%',
        magnification: '0.92x',
        screenReplace: true,
      },
      flash: {
        interlock: '디지털',
        modes: 'HS, P-TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn13, 28mm',
        redEye: true,
        release: '케이블릴리즈 CS205',
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX10,
        points: '11포인트 9크로스',
        sensitivity: '-3 ~ 18ev',
        superImpose: true,
        supersonicMotor: true,
      },
      refs: 'https://www.dpreview.com/products/pentax/slrs/pentax_k5ii, https://m.popco.net/reviewView.php?IDX=846&SUB_CAT=1&BID=dica_review',
    },
  },
  // Line 6 ==============================
  {
    type: PENTAX_DSLR_TYPE.IST,
    name: '*istD',
    line: 6,
    startYear: 2003,
    startQuarter: 3,
    endYear: 2006,
    endQuarter: 2,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronPla,
        width: 129,
        height: 95,
        depth: 60,
        weight: '510g, 배터리 포함 650g',
        verticalGrip: 'D-BG1',
      },
      mount: 'KAF2',
      power: 'AAx4, CR-V3x2, AC전원',
      memory: 'CF Type I/II, 마이크로드라이브',
      etc: '다중노출',
      comment:
        '펜탁스 최초의 디지털 바디. 아주 컴펙트한 사이즈의 중급기로 출시되었다. 한국에선 상표권 문제로 *istD 대신 zxD라는 이름으로 출시되었다. 세로그립과 싱크로율이 아주 높고, 독특한 색감과 날카로운 셔터소리가 매력적인 기종이다.',
      sensor: {
        pixels: '610만화소 CCD',
        size: PENTAX_DSLR_SENSOR_SIZE.C153,
        iso: 'ISO200-3200',
      },
      display: '11만 8000화소, 1.8인치 TFT LCD',
      imageType: 'RAW(12-bit PEF), TIFF(8-bit), JPEG',
      modes: 'M, B, P, Tv, Av, 그린',
      meteringK: '중앙중점, 스팟',
      meteringA: '16분할, 중앙중점, 스팟',
      meteringRange: '1 ~ 21.5ev',
      exposureRange: '±3ev',
      shutter: '30-1/4000sec, B',
      continuous: '2.7fps',
      continuousLength: '5장',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_PRISM,
        coverage: '95%',
        magnification: '0.95x',
      },
      flash: {
        interlock: '아날로그, 디지털',
        modes: 'W, HS, P-TTL, TTL',
        syncSpeed: '30 ~ 1/150sec, B',
        internal: 'Gn11, 28mm',
        redEye: true,
        release: '케이블릴리즈 CS205',
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX7,
        points: '11포인트',
        sensitivity: '0 ~ 19ev',
        superImpose: true,
      },
    },
  },
  {
    type: PENTAX_DSLR_TYPE.K,
    name: 'K10D',
    line: 6,
    startYear: 2006,
    startQuarter: 3,
    endYear: 2007,
    endQuarter: 4,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronPla,
        width: 142,
        height: 101,
        depth: 70,
        weight: '710g, 배터리 포함 790g',
        verticalGrip: 'D-BG2',
      },
      mount: 'KAF2',
      power: 'D-LI50 리튬이온, AC전원',
      memory: 'SD, SDHC',
      etc: '다중노출, 회전센서',
      comment:
        '*istD 이후로 새로 등장한 펜탁스의 히트작 중급기다. 바디 내장 손떨림 보정, 소니의 ICX493AQA 1020만화소 센서를 탑재했다. 카메라그랑프리 2007을 수상하고 한정판 모델도 발매했다. 한정판 모델은 고무그립 색깔이 암갈색이고, PENTAX 로고와 K10D 로고, 모드다이얼 색상이 금색이며 전용 스트랩, 한정판 세로그립을 함께 준다.',
      bonus: {
        wr: true,
        sr: '2-4스탑',
        dustRemove: '일반진동, SP코팅',
      },
      sensor: {
        pixels: '1020만화소 CCD',
        size: PENTAX_DSLR_SENSOR_SIZE.C153,
        iso: 'ISO100-1600',
        engine: ENGINE_TYPE.PRIME,
      },
      display: '21만화소, 2.5인치 TFT LCD',
      imageType: 'RAW(12-bit PEF/DNG), JPEG',
      modes: 'M, B, P, Tv, Av, TAv, Sv, USER, X',
      meteringK: '중앙중점, 스팟',
      meteringA: '16분할, 중앙중점, 스팟',
      meteringRange: '0 ~ 21ev',
      exposureRange: '±3ev',
      shutter: '30-1/4000sec, B',
      continuous: '3fps',
      continuousLength: 'JPEG 무한, RAW 9장',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_PRISM,
        coverage: '95%',
        magnification: '0.95x',
        screenReplace: true,
      },
      flash: {
        interlock: '디지털',
        modes: 'W, HS, P-TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn11, 28mm',
        redEye: true,
        release: '케이블릴리즈 CS205',
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX7,
        points: '11포인트',
        sensitivity: '-1 ~ 18ev',
        superImpose: true,
        supersonicMotor: true,
      },
    },
  },
  {
    type: PENTAX_DSLR_TYPE.K,
    name: 'K20D',
    line: 6,
    startYear: 2008,
    startQuarter: 1,
    endYear: 2009,
    endQuarter: 3,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronPla,
        width: 141.5,
        height: 101,
        depth: 70,
        weight: '715g, 배터리 포함 800g',
        verticalGrip: 'D-BG2',
      },
      mount: 'KAF2',
      power: 'D-LI50 리튬이온, AC전원',
      memory: 'SD, SDHC',
      etc: '다중노출, 회전센서',
      comment:
        '*istD 이후로 새로 등장한 펜탁스의 히트작 중급기다. 바디 내장 손떨림 보정, 소니의 ICX493AQA 1020만화소 센서를 탑재했다. 카메라그랑프리 2007을 수상하고 한정판 모델도 발매했다. 한정판 모델은 고무그립 색깔이 암갈색이고, PENTAX 로고와 K10D 로고, 모드다이얼 색상이 금색이며 전용 스트랩, 한정판 세로그립을 함께 준다.',
      bonus: {
        wr: true,
        sr: '2.5-4스탑',
        dustRemove: '일반진동, SP코팅, 먼지경고',
      },
      sensor: {
        pixels: '1460만화소 CMOS',
        size: PENTAX_DSLR_SENSOR_SIZE.C1532,
        iso: 'ISO100-3200(6400)',
        engine: ENGINE_TYPE.PRIME,
      },
      display: '23만화소, 2.7인치 TFT LCD',
      liveView: true,
      liveViewAF: '위상차',
      imageType: 'RAW(12-bit PEF/DNG), JPEG',
      modes: 'M, B, P, Tv, Av, TAv, Sv, USER, X',
      meteringK: '중앙중점, 스팟',
      meteringA: '16분할, 중앙중점, 스팟',
      meteringRange: '0 ~ 21ev',
      exposureRange: '±3ev',
      shutter: '30-1/4000sec, B',
      continuous: '3fps, 21fps burst',
      continuousLength: 'JPEG 38장, 이후로 2.3fps, RAW PEF 14장, DNG 16장까지',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_PRISM,
        coverage: '95%',
        magnification: '0.95x',
        screenReplace: true,
      },
      flash: {
        interlock: '디지털',
        modes: 'W, HS, P-TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn13, 28mm',
        redEye: true,
        release: '케이블릴리즈 CS205',
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX7,
        points: '11포인트',
        sensitivity: '-1 ~ 18ev',
        superImpose: true,
        supersonicMotor: true,
      },
    },
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'KP',
    line: 6,
    startYear: 2017,
    startQuarter: 1,
    endYear: 2021,
    endQuarter: 1,
    data: {},
  },
  // Line 7 ==============================
  {
    type: PENTAX_DSLR_TYPE.K,
    name: 'K100D',
    line: 7,
    startYear: 2006,
    startQuarter: 2,
    endYear: 2007,
    endQuarter: 2,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronPla,
        width: 129.5,
        height: 92.5,
        depth: 70,
        weight: '560g, 배터리 포함 660g',
      },
      mount: 'KAF2',
      power: 'AAx4, CR-V3x2, AC전원',
      memory: 'SD, SDHC',
      comment:
        '2006년 펜탁스의 부활을 알리는 신호탄. 옆그레이드의 극치를 달리던 *ist 시리즈를 접고 필름 시절 K 시리즈를 다시 가져왔으며, 바디 내장 손떨림 보정을 탑재하고 동급 최대의 뷰파인더를 가지고 있다. *ist에 비해 AF 속도가 약간 빨라졌다고 한다.',
      bonus: {
        sr: '2-4스탑',
      },
      sensor: {
        pixels: '610만화소 CCD',
        size: PENTAX_DSLR_SENSOR_SIZE.C153,
        iso: 'ISO200-3200',
      },
      display: '21만화소, 2.5인치 TFT LCD',
      imageType: 'RAW(12-bit PEF), JPEG',
      modes: 'M, B, P, Tv, Av, Auto, Scene',
      meteringK: '중앙중점, 스팟',
      meteringA: '16분할, 중앙중점, 스팟',
      meteringRange: '1 ~ 21.5ev',
      exposureRange: '±2ev',
      shutter: '30-1/4000sec, B',
      continuous: '2.8fps',
      continuousLength: 'JPEG 5장, RAW 3장',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_MIRROR,
        coverage: '96%',
        magnification: '0.85x',
      },
      flash: {
        interlock: '디지털',
        modes: 'W, HS, P-TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn15.6, 28mm',
        redEye: true,
        release: '케이블릴리즈 CS205',
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX7,
        points: '11포인트',
        sensitivity: '0 ~ 19ev',
        superImpose: true,
      },
    },
  },
  {
    type: PENTAX_DSLR_TYPE.K,
    name: 'K100D super',
    line: 7,
    startYear: 2007,
    startQuarter: 3,
    endYear: 2007,
    endQuarter: 4,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronPla,
        width: 129.5,
        height: 92.5,
        depth: 70,
        weight: '570g, 배터리 포함 670g',
      },
      mount: 'KAF2',
      power: 'AAx4, CR-V3x2, AC전원',
      memory: 'SD, SDHC',
      comment:
        'K100D에 SDM 접점을 추가하여 초음파모터 렌즈를 지원하게 만든 마이너 업그레이드 기종이다. 뿐만 아니라 손떨림 보정 모듈을 흔들어서 먼지를 털어내는 기능도 탑재하고 있다. 또한 이 기종부터는 공식적으로 SDHC 메모리를 지원한다.',
      bonus: {
        sr: '2-4스탑',
        dustRemove: '일반진동, SP코팅, 먼지경고',
      },
      sensor: {
        pixels: '610만화소 CCD',
        size: PENTAX_DSLR_SENSOR_SIZE.C153,
        iso: 'ISO200-3200',
      },
      display: '21만화소, 2.5인치 TFT LCD',
      imageType: 'RAW(12-bit PEF), JPEG',
      modes: 'M, B, P, Tv, Av, Auto, Scene',
      meteringK: '중앙중점, 스팟',
      meteringA: '16분할, 중앙중점, 스팟',
      meteringRange: '1 ~ 21.5ev',
      exposureRange: '±2ev',
      shutter: '30-1/4000sec, B',
      continuous: '2.8fps',
      continuousLength: 'JPEG 5장, RAW 3장',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_MIRROR,
        coverage: '96%',
        magnification: '0.85x',
      },
      flash: {
        interlock: '디지털',
        modes: 'W, HS, P-TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn15.6, 28mm',
        redEye: true,
        release: '케이블릴리즈 CS205',
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX7,
        points: '11포인트',
        sensitivity: '0 ~ 19ev',
        superImpose: true,
      },
    },
  },
  {
    type: PENTAX_DSLR_TYPE.K,
    name: 'K200D',
    line: 7,
    startYear: 2008,
    startQuarter: 1,
    endYear: 2008,
    endQuarter: 4,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronPla,
        width: 133,
        height: 95,
        depth: 74,
        weight: '630g, 배터리 포함 690g',
        verticalGrip: 'D-BG3',
      },
      mount: 'KAF2',
      power: 'AAx4(리튬, Ni-MH 포함), AC전원',
      memory: 'SD, SDHC',
      etc: '회전센서',
      comment:
        'K10D의 1020만화소 센서를 물려받은 보급 기종이다. 보급 기종 중에서는 특이하게도 방진 방습 실링처리가 되어 있고, 회전 센서를 탑재하고 있는 등 예외적인 스펙을 갖고 있다.',
      bonus: {
        wr: true,
        sr: '2.5-4스탑',
        dustRemove: '일반진동, SP코팅, 먼지경고',
      },
      sensor: {
        pixels: '1020만화소 CCD',
        size: PENTAX_DSLR_SENSOR_SIZE.C153,
        iso: 'ISO100-1600',
      },
      display: '23만화소, 2.7인치 TFT LCD',
      imageType: 'RAW(12-bit PEF/DNG), JPEG',
      modes: 'M, B, P, Tv, Av, Sv, Auto, Scene',
      meteringK: '중앙중점, 스팟',
      meteringA: '16분할, 중앙중점, 스팟',
      meteringRange: '0 ~ 21ev',
      exposureRange: '±2ev',
      shutter: '30-1/4000sec, B',
      continuous: '2.8fps',
      continuousLength: 'JPEG 4장, 이후로 1.1fps, RAW 4장까지',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_MIRROR,
        coverage: '96%',
        magnification: '0.85x',
      },
      flash: {
        interlock: '디지털',
        modes: 'W, HS, P-TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn13, 28mm',
        redEye: true,
        release: '케이블릴리즈 CS205',
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX7,
        points: '11포인트',
        sensitivity: '-1 ~ 18ev',
        superImpose: true,
        supersonicMotor: true,
      },
    },
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-30',
    line: 7,
    startYear: 2012,
    startQuarter: 2,
    endYear: 2013,
    endQuarter: 2,
    data: {},
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-50',
    line: 7,
    startYear: 2013,
    startQuarter: 3,
    endYear: 2016,
    endQuarter: 2,
    data: {},
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-70',
    line: 7,
    startYear: 2016,
    startQuarter: 3,
    endYear: 2022,
    endQuarter: 3,
    data: {},
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'KF',
    line: 7,
    startYear: 2022,
    startQuarter: 4,
    data: {},
  },
  // Line 8 ==============================
  {
    type: PENTAX_DSLR_TYPE.IST,
    name: '*istDS',
    line: 8,
    startYear: 2004,
    startQuarter: 3,
    endYear: 2005,
    endQuarter: 2,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronPla,
        width: 125,
        height: 92.5,
        depth: 66,
        weight: '505g, 배터리 포함 605g',
      },
      mount: 'KAF2',
      power: 'AAx4, CR-V3x2, AC전원',
      memory: 'SD',
      comment:
        '*istD의 마이너 기종으로 발매되었으며, 무게가 약간 더 가벼워졌다. 진득한 색감으로 인기가 있고, 저장 매체가 CF에서 SD로 변했다. 미러업 기능은 삭제되었으나 LCD 크기가 약간 커졌다.',
      sensor: {
        pixels: '610만화소 CCD',
        size: PENTAX_DSLR_SENSOR_SIZE.C153,
        iso: 'ISO200-3200',
      },
      display: '21만화소, 2.0인치 TFT LCD',
      imageType: 'RAW(12-bit PEF), JPEG',
      modes: 'M, B, P, Tv, Av, Auto',
      meteringK: '중앙중점, 스팟',
      meteringA: '16분할, 중앙중점, 스팟',
      meteringRange: '1 ~ 21.5ev',
      exposureRange: '±2ev',
      shutter: '30-1/4000sec, B',
      continuous: '2.8fps',
      continuousLength: '8장',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_PRISM,
        coverage: '95%',
        magnification: '0.95x',
        screenReplace: true,
      },
      flash: {
        interlock: '디지털',
        modes: 'W, HS, P-TTL, TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn15.6, 28mm',
        redEye: true,
        release: '케이블릴리즈 CS205',
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX7,
        points: '11포인트',
        sensitivity: '-1 ~ 18ev',
        superImpose: true,
      },
    },
  },
  {
    type: PENTAX_DSLR_TYPE.IST,
    name: '*istDS2',
    line: 8,
    startYear: 2005,
    startQuarter: 3,
    endYear: 2006,
    endQuarter: 3,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronPla,
        width: 125,
        height: 92.5,
        depth: 66,
        weight: '505g, 배터리 포함 605g',
      },
      mount: 'KAF2',
      power: 'AAx4, CR-V3x2, AC전원',
      memory: 'SD',
      comment:
        '기존 *istD에서 액정 사이즈가 커지고, AF-C 모드가 추가되었다. 같은 기종이 삼성에서 GX-1S라는 이름을 달고 발매되었다.',
      sensor: {
        pixels: '610만화소 CCD',
        size: PENTAX_DSLR_SENSOR_SIZE.C153,
        iso: 'ISO200-3200',
      },
      display: '21만화소, 2.5인치 TFT LCD',
      imageType: 'RAW(12-bit PEF), JPEG',
      modes: 'M, B, P, Tv, Av, Auto',
      meteringK: '중앙중점, 스팟',
      meteringA: '16분할, 중앙중점, 스팟',
      meteringRange: '1 ~ 21.5ev',
      exposureRange: '±2ev',
      shutter: '30-1/4000sec, B',
      continuous: '2.8fps',
      continuousLength: '8장',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_PRISM,
        coverage: '95%',
        magnification: '0.95x',
        screenReplace: true,
      },
      flash: {
        interlock: '디지털',
        modes: 'W, HS, P-TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn15.6, 28mm',
        redEye: true,
        release: '케이블릴리즈 CS205',
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX7,
        points: '11포인트',
        sensitivity: '-1 ~ 18ev',
        superImpose: true,
      },
    },
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-r',
    line: 8,
    startYear: 2010,
    startQuarter: 3,
    endYear: 2012,
    endQuarter: 2,
    // safox9
    data: {},
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-500',
    line: 8,
    startYear: 2013,
    startQuarter: 3,
    endYear: 2014,
    endQuarter: 4,
    data: {},
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-S2',
    line: 8,
    startYear: 2015,
    startQuarter: 1,
    endYear: 2018,
    endQuarter: 1,
    data: {},
  },
  // Line 9 ==============================
  {
    type: PENTAX_DSLR_TYPE.IST,
    name: '*istDL',
    line: 9,
    startYear: 2005,
    startQuarter: 1,
    endYear: 2005,
    endQuarter: 4,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronPla,
        width: 125,
        height: 92.5,
        depth: 66,
        weight: '470g, 배터리 포함 565g',
      },
      mount: 'KAF2',
      power: 'AAx4, CR-V3x2, AC전원',
      memory: 'SD',
      comment:
        '*istD의 마이너 모델로 나온 기종. 뷰파인더가 펜타프리즘에서 펜타미러로 바뀌었고, LCD 크기가 보다 커졌다. 펜탁스 디지털 바디 중 가장 가벼운 기종이다.',
      sensor: {
        pixels: '610만화소 CCD',
        size: PENTAX_DSLR_SENSOR_SIZE.C153,
        iso: 'ISO200-3200',
      },
      display: '21만화소, 2.5인치 TFT LCD',
      imageType: 'RAW(12-bit PEF), JPEG',
      modes: 'M, B, P, Tv, Av, Auto',
      meteringK: '중앙중점, 스팟',
      meteringA: '16분할, 중앙중점, 스팟',
      meteringRange: '1 ~ 21.5ev',
      exposureRange: '±2ev',
      shutter: '30-1/4000sec, B',
      continuous: '2.8fps',
      continuousLength: 'JPEG 5장, RAW 3장',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_MIRROR,
        coverage: '95%',
        magnification: '0.85x',
      },
      flash: {
        interlock: '디지털',
        modes: 'W, HS, P-TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn15.6, 28mm',
        redEye: true,
        release: '케이블릴리즈 CS205',
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX7,
        points: '3포인트',
        sensitivity: '-1 ~ 18ev',
      },
    },
  },
  {
    type: PENTAX_DSLR_TYPE.IST,
    name: '*istDL2',
    line: 9,
    startYear: 2006,
    startQuarter: 1,
    endYear: 2006,
    endQuarter: 2,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronPla,
        width: 125,
        height: 92.5,
        depth: 66,
        weight: '470g, 배터리 포함 565g',
      },
      mount: 'KAF2',
      power: 'AAx4, CR-V3x2, AC전원',
      memory: 'SD',
      comment:
        '*istD의 마이너 업그레이드 버전이다. 다이얼 등이 은색으로 바뀐게 눈에 띄고, 측거점이 3개에서 5개로 늘어났다. 같은 기종이 삼성에서 GX-1L이라는 이름을 달고 발매되었다.',
      sensor: {
        pixels: '610만화소 CCD',
        size: PENTAX_DSLR_SENSOR_SIZE.C153,
        iso: 'ISO200-3200',
      },
      display: '21만화소, 2.5인치 TFT LCD',
      imageType: 'RAW(12-bit PEF), JPEG',
      modes: 'M, B, P, Tv, Av, Auto',
      meteringK: '중앙중점, 스팟',
      meteringA: '16분할, 중앙중점, 스팟',
      meteringRange: '1 ~ 21.5ev',
      exposureRange: '±2ev',
      shutter: '30-1/4000sec, B',
      continuous: '2.8fps',
      continuousLength: 'JPEG 5장, RAW 3장',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_MIRROR,
        coverage: '95%',
        magnification: '0.85x',
      },
      flash: {
        interlock: '디지털',
        modes: 'W, HS, P-TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn15.6, 28mm',
        redEye: true,
        release: '케이블릴리즈 CS205',
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX7,
        points: '5포인트',
        sensitivity: '-1 ~ 18ev',
      },
    },
  },
  {
    type: PENTAX_DSLR_TYPE.K,
    name: 'K110D',
    line: 9,
    startYear: 2006,
    startQuarter: 3,
    endYear: 2007,
    endQuarter: 2,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronPla,
        width: 129.5,
        height: 92.5,
        depth: 70,
        weight: '485g, 배터리 포함 585g',
      },
      mount: 'KAF2',
      power: 'AAx4, CR-V3x2, AC전원',
      memory: 'SD, SDHC',
      comment: 'K100D에서 손떨림 보정 기능만 빠진 실험적인 모델이다. 국내에는 출시되지 않았다.',
      sensor: {
        pixels: '610만화소 CCD',
        size: PENTAX_DSLR_SENSOR_SIZE.C153,
        iso: 'ISO200-3200',
      },
      display: '21만화소, 2.5인치 TFT LCD',
      imageType: 'RAW(12-bit PEF), JPEG',
      modes: 'M, B, P, Tv, Av, Auto, Scene',
      meteringK: '중앙중점, 스팟',
      meteringA: '16분할, 중앙중점, 스팟',
      meteringRange: '1 ~ 21.5ev',
      exposureRange: '±2ev',
      shutter: '30-1/4000sec, B',
      continuous: '2.8fps',
      continuousLength: 'JPEG 5장, RAW 3장',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_MIRROR,
        coverage: '96%',
        magnification: '0.85x',
      },
      flash: {
        interlock: '디지털',
        modes: 'W, HS, P-TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn15.6, 28mm',
        redEye: true,
        release: '케이블릴리즈 CS205',
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX7,
        points: '11포인트',
        sensitivity: '0 ~ 19ev',
        superImpose: true,
      },
    },
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-m',
    line: 9,
    startYear: 2008,
    startQuarter: 3,
    endYear: 2009,
    endQuarter: 4,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronPla,
        width: 122.5,
        height: 91.5,
        depth: 67.5,
        weight: '525g, 배터리 포함 590g',
      },
      mount: 'KAF3',
      power: 'AAx4(리튬, Ni-MH 포함), AC전원',
      memory: 'SD, SDHC',
      comment:
        '펜탁스가 호야에게 인수되고 나서 처음으로 나온 모델이다. APS-C 포멧 DSLR 카메라중에선 가장 작은 크기다. 미주지역에선 K2000이라는 이름으로 발매되었다. 흰색과 올리브그린 등의 색으로 한정판이 발매되었으며, 초저가로 나온 모델이다. K-m과 더불어 경량형의 DA L 렌즈들도 발매되었다. 그간 정체상태였던 AF 성능미 개선되어 저광량에서 버벅임이 많이 줄어들었다.',
      bonus: {
        sr: '4스탑',
        dustRemove: '일반진동, SP코팅, 먼지경고',
      },
      sensor: {
        pixels: '1020만화소 CCD',
        size: PENTAX_DSLR_SENSOR_SIZE.C153,
        iso: 'ISO100-3200',
      },
      display: '23만화소, 2.7인치 TFT LCD',
      imageType: 'RAW(12-bit PEF/DNG), JPEG',
      modes: 'M, B, P, Tv, Av, Sv, Auto, Scene',
      meteringK: '중앙중점, 스팟',
      meteringA: '16분할, 중앙중점, 스팟',
      meteringRange: '0 ~ 21ev',
      exposureRange: '±2ev',
      shutter: '30-1/4000sec, B',
      continuous: '3.5fps에서 JPEG 5장, RAW 4장',
      continuousLength: '1.1fps에서 JPEG 무한, RAW 7장',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_MIRROR,
        coverage: '96%',
        magnification: '0.85x',
      },
      flash: {
        interlock: '디지털',
        modes: 'W, HS, P-TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn11, 28mm',
        redEye: true,
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX7,
        points: '11포인트',
        sensitivity: '-1 ~ 18ev',
        superImpose: true,
        supersonicMotor: true,
      },
    },
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-x',
    line: 9,
    startYear: 2010,
    startQuarter: 1,
    endYear: 2011,
    endQuarter: 1,
    data: {
      body: {
        material: PENTAX_DSLR_MATERIAL.IronPla,
        width: 122.5,
        height: 91.5,
        depth: 67.5,
        weight: '515g, 배터리 포함 580g',
      },
      mount: 'KAF3',
      power: 'AAx4(리튬, Ni-MH 포함), AC전원',
      memory: 'SD, SDHC',
      etc: '다중노출',
      comment:
        'K-m 후계기로 나온 히트작 보급기. 똑같은 외관에 무게는 오히려 더 줄어들었지만, 셔터속도를 1/4000에서 1/6000으로 올리고, 소니의 1200만화소 CMOS 센서를 사용하여 화질이 상급기인 K-7보다도 오히려 뛰어나다. 동영상 촬영 기능을 지원하며, 기능에 비해 파격적인 가격으로 출시되었다. 바디 색상을 무려 100가지나 지원한다. 한정판으로 코레자나이로보 에디션이 출시되었다. 수퍼임포즈가 없어 아쉽다는 평이 많다.',
      bonus: {
        sr: '4스탑',
        dustRemove: '일반진동, SP코팅, 먼지경고',
      },
      sensor: {
        pixels: '1240만화소 CMOS',
        size: PENTAX_DSLR_SENSOR_SIZE.C1533,
        iso: 'ISO200-6400(100-12800)',
        engine: ENGINE_TYPE.PRIME2,
      },
      display: '23만화소, 2.7인치 TFT LCD',
      liveView: true,
      liveViewAF: '컨트라스트, 얼굴인식, 위상차',
      movie: '1280x720p, 24fps',
      movieType: 'M-JPEG',
      imageType: 'RAW(12-bit PEF/DNG), JPEG',
      modes: 'M, P, Tv, Av, Sv, Auto, Scene, Movie',
      meteringK: '중앙중점, 스팟',
      meteringA: '16분할, 중앙중점, 스팟',
      meteringRange: '1 ~ 21.5ev',
      exposureRange: '±3ev',
      shutter: '30-1/6000sec, B',
      continuous: '4.7fps에서 JPEG 17장, RAW 5장',
      continuousLength: '2fps에서 JPEG 무한, RAW 11장',
      viewFinder: {
        type: OPTICS_TYPE.PENTA_MIRROR,
        coverage: '96%',
        magnification: '0.85x',
      },
      flash: {
        interlock: '디지털',
        modes: 'W, HS, P-TTL',
        syncSpeed: '30 ~ 1/180sec, B',
        internal: 'Gn16, 28mm',
        redEye: true,
        releaseW: '리모트릴리즈 F',
      },
      focus: {
        name: FOCUS_NAME.SAFOX7,
        points: '11포인트',
        sensitivity: '-1 ~ 18ev',
        supersonicMotor: true,
      },
    },
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-S1',
    line: 9,
    startYear: 2014,
    startQuarter: 2,
    endYear: 2016,
    endQuarter: 2,
    data: {},
  },
  // Line 10 =============================
  {
    type: PENTAX_DSLR_TYPE.SHIT,
    name: 'K-01',
    line: 10,
    startYear: 2012,
    startQuarter: 1,
    endYear: 2013,
    endQuarter: 1,
    data: {},
  },
  // Line 11 =============================
  {
    type: PENTAX_DSLR_TYPE.Q,
    name: 'Q7',
    line: 11,
    startYear: 2013,
    startQuarter: 2,
    endYear: 2015,
    endQuarter: 2,
    data: {},
  },
  // Line 12 =============================
  {
    type: PENTAX_DSLR_TYPE.Q,
    name: 'Q-S1',
    line: 12,
    startYear: 2014,
    startQuarter: 3,
    endYear: 2020,
    endQuarter: 1,
    data: {},
  },
  // Line 13 =============================
  {
    type: PENTAX_DSLR_TYPE.Q,
    name: 'Q',
    line: 13,
    startYear: 2011,
    startQuarter: 2,
    endYear: 2012,
    endQuarter: 2,
    data: {},
  },
  {
    type: PENTAX_DSLR_TYPE.Q,
    name: 'Q10',
    line: 13,
    startYear: 2012,
    startQuarter: 3,
    endYear: 2014,
    endQuarter: 3,
    data: {},
  },
];
