import {
  CameraType,
  CAMERA_MAKER,
  // OPTICS_TYPE,
  // SENSOR_TYPE,
  // SENSOR_SIZE,
  // FOCUS_NAME,
  // VIDEO_SCAN_TYPE,
  // ENGINE_TYPE,
  MOUNT,
  GRADE,
} from '@/types/cameras.d';

// https://en.wikipedia.org/wiki/Lumix
// https://en.wikipedia.org/wiki/Template:Micro_Four_Thirds_cameras

export const PANASONICS: CameraType[] = [
  // 1995 =============================================
  // 1996 =============================================
  // 1997 =============================================
  // 1998 =============================================
  // 1999 =============================================
  // 2000 =============================================
  // 2001 =============================================
  // 2002 =============================================
  // 2003 =============================================
  // 2004 =============================================
  // 2005 =============================================
  // 2006 =============================================
  // 2007 =============================================
  // 2008 =============================================
  {
    year: 2008,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'G1',
    predecessor: [],
    successor: ['G2'],

    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2009 =============================================
  {
    year: 2009,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ADVANCED,
    name: 'GH1',
    predecessor: [],
    successor: ['GH2'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2009,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRY,
    name: 'GF1',
    predecessor: [],
    successor: ['GF2'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2010 =============================================
  {
    year: 2010,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ADVANCED,
    name: 'GH2',
    predecessor: ['GH1'],
    successor: ['GH3'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2010,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'G2',
    predecessor: ['G1'],
    successor: ['G3'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2010,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRY,
    name: 'G10',
    predecessor: [],
    successor: ['G100'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2010,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRY,
    name: 'GF2',
    predecessor: ['GF1'],
    successor: ['GF3'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2011 =============================================
  {
    year: 2011,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ADVANCED,
    name: 'GX1',
    predecessor: [],
    successor: ['GX7'],

    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2011,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'G3',
    predecessor: ['G2'],
    successor: ['G5'],

    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2011,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRY,
    name: 'GF3',
    predecessor: ['GF2'],
    successor: ['GF5'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2012 =============================================
  {
    year: 2012,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ADVANCED,
    name: 'GH3',
    predecessor: ['GH2'],
    successor: ['GH4'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2012,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'G5',
    predecessor: ['G3'],
    successor: ['G6'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2012,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRY,
    name: 'GF5',
    predecessor: ['GF3'],
    successor: ['GF6'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2013 =============================================
  {
    year: 2013,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'G6',
    predecessor: ['G5'],
    successor: ['G7'],

    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2013,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ADVANCED,
    name: 'GX7',
    predecessor: ['GX1'],
    successor: ['GX8'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2013,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'GM1',
    predecessor: [],
    successor: ['GM5'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2013,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRY,
    name: 'GF6',
    predecessor: ['GF5'],
    successor: ['GF7'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2014 =============================================
  {
    year: 2014,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ADVANCED,
    name: 'GH4',
    predecessor: ['GH3'],
    successor: ['GH5'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2014,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'GM5',
    predecessor: ['GM1'],
    successor: ['GX80'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2015 =============================================
  {
    year: 2015,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ADVANCED,
    name: 'GX8',
    predecessor: ['GX7'],
    successor: ['GX9'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2015,
    maker: CAMERA_MAKER.PANASONIC,
    name: 'G7',
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    predecessor: ['G6'],
    successor: ['G80'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2015,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRY,
    name: 'GF7',
    predecessor: ['GF6'],
    successor: ['GF8'],

    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2016 =============================================
  {
    year: 2016,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'G80',
    otherNames: ['G85'],
    predecessor: ['G7'],
    successor: ['G90'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2016,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'GX80',
    predecessor: ['GM5'],
    successor: [],
    otherNames: ['GX85'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  {
    year: 2016,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRY,
    name: 'GF8',
    predecessor: ['GF7'],
    successor: ['GF9'],

    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2017 =============================================
  {
    year: 2017,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.PROFESSIONAL,
    name: 'G9',
    otherNames: [],
    predecessor: [],
    successor: [],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2017,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ADVANCED,
    name: 'GH5',
    predecessor: ['GH4'],
    successor: ['GH5 II'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2017,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRY,
    name: 'GF9',
    predecessor: ['GF8'],
    successor: ['GF10'],
    otherNames: ['GX500', 'GX800'],

    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2018 =============================================
  {
    year: 2018,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.PROFESSIONAL,
    name: 'GH5S',
    otherNames: [],
    predecessor: [],
    successor: ['GH6'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2018,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ADVANCED,
    name: 'GX9',
    predecessor: ['GX8'],
    successor: [],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2019 =============================================
  {
    year: 2019,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.LeicaL,
    grade: GRADE.FLAGSHIP,
    name: 'S1',
    predecessor: [],
    successor: [],

    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2019,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.LeicaL,
    grade: GRADE.FLAGSHIP,
    name: 'S1R',
    predecessor: [],
    successor: [],

    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2019,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.LeicaL,
    grade: GRADE.FLAGSHIP,
    name: 'S1H',
    predecessor: [],
    successor: [],

    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2019,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.MIDRANGE,
    name: 'G90',
    otherNames: ['G95'],
    predecessor: ['G80'],
    successor: [],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2019,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRY,
    name: 'GF10',
    predecessor: ['GF9'],
    successor: [],
    otherNames: ['GF90'],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2020 =============================================
  {
    year: 2020,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.LeicaL,
    grade: GRADE.ADVANCED,
    name: 'S5',
    predecessor: [],
    successor: ['S5 II'],

    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2020,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ENTRY,
    name: 'G100',
    predecessor: ['G10'],
    successor: [],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2021 =============================================
  {
    year: 2021,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.ADVANCED,
    name: 'GH5 II',
    predecessor: ['GH5'],
    successor: [],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2022 =============================================
  {
    year: 2022,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.MFourThird,
    grade: GRADE.PROFESSIONAL,
    name: 'GH6',
    predecessor: ['GH5S'],
    successor: [],
    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },

  // 2023 =============================================
  {
    year: 2023,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.LeicaL,
    grade: GRADE.ADVANCED,
    name: 'S5 II',
    predecessor: ['S5'],
    successor: [],

    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
  {
    year: 2023,
    maker: CAMERA_MAKER.PANASONIC,
    mount: MOUNT.LeicaL,
    grade: GRADE.ADVANCED,
    name: 'S5 II X',
    predecessor: ['S5'],
    successor: [],

    // sensor: {
    //   size: SENSOR_SIZE.FF,
    //   engine: ENGINE_TYPE.EXPEED4,
    //   pixelsFamiliar: '16.2M',
    //   type: SENSOR_TYPE.CMOS,
    //   isoMin: 100,
    //   isoMax: 409600,
    // },
  },
];
