import { PENTAX_DSLR_TYPE } from '@/types/pentaxes.d';

export const YEAR_INFO = {
  start: 2003,
  end: 2023,
};

export const PENTAX_DSLRS = [
  // Line 1 ==============================
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: '645D',
    line: 1,
    startYear: 2010,
    startQuarter: 2,
    endYear: 2014,
    endQuarter: 1,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: '645Z',
    line: 1,
    startYear: 2014,
    startQuarter: 2,
  },
  // Line 2 ==============================
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-1',
    line: 2,
    startYear: 2016,
    startQuarter: 2,
    endYear: 2018,
    endQuarter: 1,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-1 II',
    line: 2,
    startYear: 2018,
    startQuarter: 2,
  },
  // Line 3 / 4 ==============================
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-3',
    line: 4,
    startYear: 2013,
    startQuarter: 4,
    endYear: 2016,
    endQuarter: 4,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-3 II',
    line: 3,
    startYear: 2015,
    startQuarter: 3,
    endYear: 2018,
    endQuarter: 1,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-3 III',
    line: 3,
    startYear: 2021,
    startQuarter: 2,
  },
  // Line 5 ==============================
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-7',
    line: 5,
    startYear: 2009,
    startQuarter: 2,
    endYear: 2010,
    endQuarter: 3,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-5',
    line: 5,
    startYear: 2010,
    startQuarter: 4,
    endYear: 2012,
    endQuarter: 2,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-5 II / K-5 IIs',
    line: 5,
    startYear: 2012,
    startQuarter: 3,
    endYear: 2014,
    endQuarter: 4,
  },
  // Line 6 ==============================
  {
    type: PENTAX_DSLR_TYPE.IST,
    name: '*istD',
    line: 6,
    startYear: 2003,
    startQuarter: 3,
    endYear: 2006,
    endQuarter: 2,
  },
  {
    type: PENTAX_DSLR_TYPE.K,
    name: 'K10D',
    line: 6,
    startYear: 2006,
    startQuarter: 3,
    endYear: 2007,
    endQuarter: 4,
  },
  {
    type: PENTAX_DSLR_TYPE.K,
    name: 'K20D',
    line: 6,
    startYear: 2008,
    startQuarter: 1,
    endYear: 2009,
    endQuarter: 3,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'KP',
    line: 6,
    startYear: 2017,
    startQuarter: 1,
    endYear: 2021,
    endQuarter: 1,
  },
  // Line 7 ==============================
  {
    type: PENTAX_DSLR_TYPE.K,
    name: 'K100D',
    line: 7,
    startYear: 2006,
    startQuarter: 2,
    endYear: 2007,
    endQuarter: 2,
  },
  {
    type: PENTAX_DSLR_TYPE.K,
    name: 'K100D super',
    line: 7,
    startYear: 2007,
    startQuarter: 3,
    endYear: 2007,
    endQuarter: 4,
  },
  {
    type: PENTAX_DSLR_TYPE.K,
    name: 'K200D',
    line: 7,
    startYear: 2008,
    startQuarter: 1,
    endYear: 2008,
    endQuarter: 4,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-30',
    line: 7,
    startYear: 2012,
    startQuarter: 2,
    endYear: 2013,
    endQuarter: 2,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-50',
    line: 7,
    startYear: 2013,
    startQuarter: 3,
    endYear: 2016,
    endQuarter: 2,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-70',
    line: 7,
    startYear: 2016,
    startQuarter: 3,
    endYear: 2022,
    endQuarter: 3,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'KF',
    line: 7,
    startYear: 2022,
    startQuarter: 4,
  },
  // Line 8 ==============================
  {
    type: PENTAX_DSLR_TYPE.IST,
    name: '*istDS',
    line: 8,
    startYear: 2004,
    startQuarter: 3,
    endYear: 2005,
    endQuarter: 2,
  },
  {
    type: PENTAX_DSLR_TYPE.IST,
    name: '*istDS2',
    line: 8,
    startYear: 2005,
    startQuarter: 3,
    endYear: 2006,
    endQuarter: 3,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-r',
    line: 8,
    startYear: 2010,
    startQuarter: 3,
    endYear: 2012,
    endQuarter: 2,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-500',
    line: 8,
    startYear: 2013,
    startQuarter: 3,
    endYear: 2014,
    endQuarter: 4,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-S2',
    line: 8,
    startYear: 2015,
    startQuarter: 1,
    endYear: 2018,
    endQuarter: 1,
  },
  // Line 9 ==============================
  {
    type: PENTAX_DSLR_TYPE.IST,
    name: '*istDL',
    line: 9,
    startYear: 2005,
    startQuarter: 1,
    endYear: 2005,
    endQuarter: 4,
  },
  {
    type: PENTAX_DSLR_TYPE.IST,
    name: '*istDL2',
    line: 9,
    startYear: 2006,
    startQuarter: 1,
    endYear: 2006,
    endQuarter: 2,
  },
  {
    type: PENTAX_DSLR_TYPE.K,
    name: 'K110D',
    line: 9,
    startYear: 2006,
    startQuarter: 3,
    endYear: 2007,
    endQuarter: 2,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-m',
    line: 9,
    startYear: 2008,
    startQuarter: 3,
    endYear: 2009,
    endQuarter: 4,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-x',
    line: 9,
    startYear: 2010,
    startQuarter: 1,
    endYear: 2011,
    endQuarter: 1,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-S1',
    line: 9,
    startYear: 2014,
    startQuarter: 2,
    endYear: 2016,
    endQuarter: 2,
  },
  // Line 10 =============================
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'K-01',
    line: 10,
    startYear: 2012,
    startQuarter: 1,
    endYear: 2013,
    endQuarter: 1,
  },
  // Line 11 =============================
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'Q7',
    line: 11,
    startYear: 2013,
    startQuarter: 2,
    endYear: 2015,
    endQuarter: 2,
  },
  // Line 12 =============================
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'Q-S1',
    line: 12,
    startYear: 2014,
    startQuarter: 3,
    endYear: 2020,
    endQuarter: 1,
  },
  // Line 13 =============================
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'Q',
    line: 13,
    startYear: 2011,
    startQuarter: 2,
    endYear: 2012,
    endQuarter: 2,
  },
  {
    type: PENTAX_DSLR_TYPE.NEW_K,
    name: 'Q10',
    line: 13,
    startYear: 2012,
    startQuarter: 3,
    endYear: 2014,
    endQuarter: 3,
  },
];
