import { IdolCore } from '@/types/idols.d';

export const Y1996: IdolCore[] = [
  // 1996 === === === === ===
  {
    debutYear: '1996',
    endYear: '2010',
    name: '구피',
    category: 'boy-group',
    youtubeUrl: 'K5lViE7-4-c',
    youtubeStartsAt: 142,
    descNamu: 'https://namu.wiki/w/%EA%B5%AC%ED%94%BC(%EC%9D%8C%EC%95%85%20%EA%B7%B8%EB%A3%B9)',
    descVibe: 'https://vibe.naver.com/artist/10',
    descMelon: 'https://www.melon.com/artist/timeline.htm?artistId=100023',
  },
  {
    debutYear: '1996',
    endYear: '활동중',
    name: '김연우',
    category: 'boy-solo',
    youtubeUrl: 'wxxb311BWRM',
    youtubeStartsAt: 128,
    descNamu: 'https://namu.wiki/w/%EA%B9%80%EC%97%B0%EC%9A%B0',
    descVibe: 'https://vibe.naver.com/artist/30',
    descMelon: 'https://www.melon.com/artist/timeline.htm?artistId=6017',
  },
  {
    debutYear: '1996',
    endYear: '2006',
    name: '뚜띠',
    category: 'girl-group',
    youtubeUrl: 'diCkr2E3vVA',
    youtubeStartsAt: 180,
    descVibe: 'https://vibe.naver.com/artist/10782',
    descMelon: 'https://www.melon.com/artist/timeline.htm?artistId=100155',
  },
  {
    debutYear: '1996',
    name: '리아',
    category: 'girl-solo',
    descNamu: 'https://namu.wiki/w/%EB%A6%AC%EC%95%84(%EA%B0%80%EC%88%98)',
  },
  {
    debutYear: '1996',
    name: '소찬휘',
    category: 'girl-solo',
    youtubeUrl: 'o1RFSX5Epmo',
    youtubeStartsAt: 110,
    descNamu: 'https://namu.wiki/w/%EC%86%8C%EC%B0%AC%ED%9C%98',
    descVibe: 'https://vibe.naver.com/artist/127',
    descMelon: 'https://www.melon.com/artist/timeline.htm?artistId=3897',
  },
  {
    debutYear: '1996',
    name: '양파',
    category: 'girl-solo',
    youtubeUrl: 'euodkPs-JMA',
    youtubeStartsAt: 63,
    descNamu: 'https://namu.wiki/w/%EC%96%91%ED%8C%8C(%EA%B0%80%EC%88%98)',
  },
  {
    debutYear: '1996',
    endYear: '1999',
    name: '언타이틀',
    category: 'boy-group',
    youtubeUrl: '4g6Hi6ydWnI',
    youtubeStartsAt: 149,
    descTitle: '유건형과 서정환으로 구성된 대한민국의 실력파 듀오',
    descNamu: 'https://namu.wiki/w/%EC%96%B8%ED%83%80%EC%9D%B4%ED%8B%80',
    descVibe: 'https://vibe.naver.com/artist/159',
    descMelon: 'https://www.melon.com/artist/timeline.htm?artistId=100042',
  },
  {
    debutYear: '1996',
    name: '에코',
    category: 'girl-solo',
    descNamu: 'https://namu.wiki/w/%EC%97%90%EC%BD%94(%EA%B1%B8%EA%B7%B8%EB%A3%B9)',
  },
  {
    debutYear: '1996',
    endYear: '2011',
    name: '영턱스클럽',
    category: 'mixed-group',
    youtubeUrl: 'qB2sh9dKLQw',
    youtubeStartsAt: 86,
    descTitle: '서태지와 아이들 출신의 이주노가 프로듀싱한 혼성 댄스 그룹',
    descNamu: 'https://namu.wiki/w/%EC%98%81%ED%84%B1%EC%8A%A4%ED%81%B4%EB%9F%BD',
    descVibe: 'https://vibe.naver.com/artist/164',
    descMelon: 'https://www.melon.com/artist/timeline.htm?artistId=100045',
  },
  {
    debutYear: '1996',
    name: '이지훈',
    category: 'boy-solo',
    descNamu:
      'https://namu.wiki/w/%EC%9D%B4%EC%A7%80%ED%9B%88(%EB%A9%80%ED%8B%B0%20%EC%97%94%ED%84%B0%ED%85%8C%EC%9D%B4%EB%84%88)',
  },
  {
    debutYear: '1996',
    endYear: '활동중',
    name: '이현도',
    category: 'boy-solo',
    youtubeUrl: 'EuEDha_el4A',
    youtubeStartsAt: 298,
    descNamu: 'https://namu.wiki/w/%EC%9D%B4%ED%98%84%EB%8F%84',
    descVibe: 'https://vibe.naver.com/artist/213',
    descMelon: 'https://www.melon.com/artist/timeline.htm?artistId=3614',
  },
  {
    debutYear: '1996',
    endYear: '2010',
    name: '자자',
    category: 'mixed-group',
    youtubeUrl: 'R3DbYFoqGr8',
    youtubeStartsAt: 41,
    descNamu: 'https://namu.wiki/w/%EC%9E%90%EC%9E%90(%ED%98%BC%EC%84%B1%EA%B7%B8%EB%A3%B9)',
    descVibe: 'https://vibe.naver.com/artist/9579',
    descMelon: 'https://www.melon.com/artist/timeline.htm?artistId=100101',
  },
  {
    debutYear: '1996',
    endYear: '2001',
    name: '주주클럽',
    category: 'mixed-group',
    youtubeUrl: 'CkM1TcQ1o64',
    youtubeStartsAt: 46,
    descTitle: '톡톡 튀는 음악과 자유로운 무대매너로 신선한 충격을 전해줬던 대한민국의 3인조 모던 록 밴드',
    descNamu: 'https://namu.wiki/w/%EC%A3%BC%EC%A3%BC%ED%81%B4%EB%9F%BD',
    descVibe: 'https://vibe.naver.com/artist/253',
    descMelon: 'https://www.melon.com/artist/timeline.htm?artistId=100053',
  },
  {
    debutYear: '1996',
    endYear: '1997',
    name: '콜라',
    category: 'mixed-group',
    youtubeUrl: 'sigUTJ46jTs',
    youtubeStartsAt: 118,
    descNamu: 'https://namu.wiki/w/%EC%BD%9C%EB%9D%BC(%EA%B0%80%EC%88%98)',
    descVibe: 'https://vibe.naver.com/artist/1585',
    descMelon: 'https://www.melon.com/artist/timeline.htm?artistId=101793',
  },
  {
    debutYear: '1996',
    endYear: '1997',
    name: '하모하모',
    category: 'boy-group',
    descVibe: 'https://vibe.naver.com/artist/9490',
    descMelon: 'https://www.melon.com/artist/timeline.htm?artistId=100178',
  },
  {
    debutYear: '1996',
    endYear: '2001',
    name: 'H.O.T',
    category: 'boy-group',
    youtubeUrl: 'i54a8uRJOp4',
    youtubeStartsAt: 92,
    descTitle: '서태지 이후 본격적인 아이돌 전성시대의 왕조를 세움',
    descNamu: 'https://namu.wiki/w/H.O.T.',
    descVibe: 'https://vibe.naver.com/artist/314',
    descMelon: 'https://www.melon.com/artist/timeline.htm?artistId=100008',
  },
  {
    debutYear: '1996',
    endYear: '1997',
    name: 'IDOL',
    category: 'boy-group',
    youtubeUrl: 'vD_0UwJ9r5k',
    youtubeStartsAt: 60,
    descNamu: 'https://namu.wiki/w/IDOL',
    descMelon: 'https://www.melon.com/artist/timeline.htm?artistId=101640',
  },
  {
    debutYear: '1996',
    endYear: '1999',
    name: 'UP',
    category: 'mixed-group',
    youtubeUrl: 'W26H4SDa19U',
    youtubeStartsAt: 167,
    descTitle: '중학생 멤버들의 귀여운 용모를 전면에 내세운 4인조 댄스 그룹',
    descNamu: 'https://namu.wiki/w/UP',
    descVibe: 'https://vibe.naver.com/artist/336',
    descMelon: 'https://www.melon.com/artist/timeline.htm?artistId=100019',
  },
];
