import { IdolCore } from '@/types/idols.d';

export const Y1997: IdolCore[] = [
  // 1997 === === === === ===
  {
    debutYear: '1997',
    name: '고구려',
    category: 'mixed-group',
  },
  {
    debutYear: '1997',
    name: '디바',
    category: 'girl-group',
    youtubeUrl: '_6pEn8RvESA',
    youtubeStartsAt: 24,
    descNamu: 'https://namu.wiki/w/디바(가수)',
  },
  {
    debutYear: '1997',
    name: '박완규',
    category: 'boy-solo',
    descNamu: 'https://namu.wiki/w/%EB%B0%95%EC%99%84%EA%B7%9C',
  },
  {
    debutYear: '1997',
    name: '박지윤',
    category: 'girl-solo',
    youtubeUrl: 'rAsMh0zyH3o',
    youtubeStartsAt: 156,
    descNamu:
      'https://namu.wiki/w/%EB%B0%95%EC%A7%80%EC%9C%A4(%EB%A9%80%ED%8B%B0%20%EC%97%94%ED%84%B0%ED%85%8C%EC%9D%B4%EB%84%88)',
  },
  {
    debutYear: '1997',
    name: '베이비복스',
    category: 'girl-group',
    youtubeUrl: 'Qa5ve47TD4E',
    youtubeStartsAt: 64,
    descNamu: 'https://namu.wiki/w/%EB%B2%A0%EC%9D%B4%EB%B9%84%EB%B3%B5%EC%8A%A4',
  },
  {
    debutYear: '1997',
    name: '소호대',
    category: 'mixed-group',
  },
  {
    debutYear: '1997',
    name: '스페이스A',
    category: 'mixed-group',
    youtubeUrl: 'ps-2nZtdAZQ',
    youtubeStartsAt: 155,
    descNamu: 'https://namu.wiki/w/%EC%8A%A4%ED%8E%98%EC%9D%B4%EC%8A%A4%20%EC%97%90%EC%9D%B4',
  },
  {
    debutYear: '1997',
    name: '얀',
    category: 'boy-solo',
    youtubeUrl: '_k-A0RULIPI',
    youtubeStartsAt: 89,
    descNamu: 'https://namu.wiki/w/%EC%96%80(%EA%B0%80%EC%88%98)',
  },
  {
    debutYear: '1997',
    endYear: '도주',
    name: '유승준',
    category: 'boy-solo',
    youtubeUrl: '0IA6HHiFjec',
    youtubeStartsAt: 102,
    descNamu: 'https://namu.wiki/w/%EC%8A%A4%ED%8B%B0%EB%B8%8C%20%EC%9C%A0',
  },
  {
    debutYear: '1997',
    name: '자우림',
    category: 'mixed-group',
    youtubeUrl: '0UpMpuf3o8E',
    youtubeStartsAt: 1,
    descNamu: 'https://namu.wiki/w/%EC%9E%90%EC%9A%B0%EB%A6%BC',
  },
  {
    debutYear: '1997',
    name: '젝스키스',
    category: 'boy-group',
    youtubeUrl: '-MM1dcwAWIY',
    youtubeStartsAt: 83,
    descNamu: 'https://namu.wiki/w/%EC%A0%9D%EC%8A%A4%ED%82%A4%EC%8A%A4',
  },
  {
    debutYear: '1997',
    name: '줄리엣',
    category: 'mixed-group',
  },
  {
    debutYear: '1997',
    name: '지누션',
    category: 'boy-group',
    youtubeUrl: 'kuVtFzeEjF8',
    youtubeStartsAt: 13,
    descNamu: 'https://namu.wiki/w/%EC%A7%80%EB%88%84%EC%85%98',
  },
  {
    debutYear: '1997',
    name: '태사자',
    category: 'boy-group',
    youtubeUrl: 'du8X6K6jCRA',
    youtubeStartsAt: 1,
    descNamu: 'https://namu.wiki/w/%ED%83%9C%EC%82%AC%EC%9E%90(%EC%95%84%EC%9D%B4%EB%8F%8C)',
  },
  {
    debutYear: '1997',
    name: '홍경민',
    category: 'boy-solo',
    youtubeUrl: 'v2j9WCHVG8A',
    youtubeStartsAt: 91,
    descNamu: 'https://namu.wiki/w/%ED%99%8D%EA%B2%BD%EB%AF%BC',
  },
  {
    debutYear: '1997',
    name: 'NRG',
    category: 'boy-group',
    youtubeUrl: 'Qk7975XcK-g',
    youtubeStartsAt: 62,
    descNamu: 'https://namu.wiki/w/NRG(%EC%95%84%EC%9D%B4%EB%8F%8C)',
  },
  {
    debutYear: '1997',
    name: 'S.E.S',
    category: 'girl-group',
    youtubeUrl: 'guTWZjpy5CI',
    youtubeStartsAt: 10,
    descNamu: 'https://namu.wiki/w/S.E.S.',
  },
  {
    debutYear: '1997',
    name: 'TNB',
    category: 'boy-group',
  },
  {
    debutYear: '1997',
    name: 'UNO',
    category: 'boy-group',
  },
];
