import { IdolCore } from '@/types/idols.d';

export const Y1998: IdolCore[] = [
  // 1998 === === === === ===
  {
    debutYear: '1998',
    name: '1TYM',
    category: 'boy-group',
    youtubeUrl: 'gh2B1RtJbXg',
    youtubeStartsAt: 147,
    descNamu: 'https://namu.wiki/w/%EC%9B%90%ED%83%80%EC%9E%84(%EA%B7%B8%EB%A3%B9)',
  },
  {
    debutYear: '1998',
    name: '김현정',
    category: 'girl-solo',
    youtubeUrl: 'N7VBSaZ-jKQ',
    youtubeStartsAt: 87,
    descNamu: 'https://namu.wiki/w/%EA%B9%80%ED%98%84%EC%A0%95(1976)',
  },
  {
    debutYear: '1998',
    name: '박기영',
    category: 'girl-solo',
    descNamu: 'https://namu.wiki/w/%EB%B0%95%EA%B8%B0%EC%98%81',
  },
  {
    debutYear: '1998',
    name: '박정현',
    category: 'girl-solo',
    descNamu: 'https://namu.wiki/w/%EB%B0%95%EC%A0%95%ED%98%84',
  },
  {
    debutYear: '1998',
    name: '루머스',
    category: 'girl-solo',
  },
  {
    debutYear: '1998',
    name: 'S#ARP',
    category: 'mixed-group',
    youtubeUrl: 'n_28BGqfvE8',
    youtubeStartsAt: 79,
    descNamu: 'https://namu.wiki/w/S%23ARP',
  },
  {
    debutYear: '1998',
    name: '코요태',
    category: 'mixed-group',
    youtubeUrl: 'I60XdW1QTeQ',
    youtubeStartsAt: 118,
    descNamu: 'https://namu.wiki/w/%EC%BD%94%EC%9A%94%ED%83%9C',
  },
  {
    debutYear: '1998',
    name: '비쥬',
    category: 'mixed-group',
    descNamu: 'https://namu.wiki/w/%EB%B9%84%EC%A5%AC(%EA%B0%80%EC%88%98)',
  },
  {
    debutYear: '1998',
    name: '오룡비무방',
    category: 'mixed-group',
  },
  {
    debutYear: '1998',
    name: '핑클',
    category: 'girl-group',
    youtubeUrl: 'CRR9Wsqf8Ls',
    youtubeStartsAt: 101,
    descNamu: 'https://namu.wiki/w/%ED%95%91%ED%81%B4',
  },
  {
    debutYear: '1998',
    name: '한스밴드',
    category: 'girl-group',
    youtubeUrl: '4Mrf75nDAwU',
    youtubeStartsAt: 12,
    descNamu: 'https://namu.wiki/w/%ED%95%9C%EC%8A%A4%EB%B0%B4%EB%93%9C',
  },
  {
    debutYear: '1998',
    name: '써클',
    category: 'girl-group',
    descNamu: 'https://namu.wiki/w/%EC%8D%A8%ED%81%B4(%EC%95%84%EC%9D%B4%EB%8F%8C)',
  },
  {
    debutYear: '1998',
    name: '신화',
    category: 'boy-group',
    youtubeUrl: 'YxlXwKY825I',
    youtubeStartsAt: 64,
    descNamu: 'https://namu.wiki/w/%EC%8B%A0%ED%99%94(%EC%95%84%EC%9D%B4%EB%8F%8C)',
  },
  {
    debutYear: '1998',
    name: 'EVE',
    category: 'boy-group',
    youtubeUrl: '5j8JqkOZc2k',
    youtubeStartsAt: 73,
    descNamu: 'https://namu.wiki/w/%EC%9D%B4%EB%B8%8C(%EB%A1%9D%EB%B0%B4%EB%93%9C)',
  },
  {
    debutYear: '1998',
    name: '팬클럽',
    category: 'boy-group',
    descNamu: 'https://namu.wiki/w/%ED%8C%AC%ED%81%B4%EB%9F%BD#s-2',
  },
  {
    debutYear: '1998',
    name: '이글파이브',
    category: 'boy-group',
  },
  {
    debutYear: '1998',
    name: 'OPPA',
    category: 'boy-group',
    descNamu: 'https://namu.wiki/w/OPPA',
  },
  {
    debutYear: '1998',
    name: '스피드',
    category: 'boy-group',
  },
  {
    debutYear: '1998',
    name: '포맨',
    category: 'boy-group',
    descNamu: 'https://namu.wiki/w/4MEN',
  },
  {
    debutYear: '1998',
    name: 'J.ae',
    category: 'girl-solo',
    youtubeUrl: '2W0QV_G-7_w',
    youtubeStartsAt: 125,
    descNamu: 'https://namu.wiki/w/J.ae',
  },
  {
    debutYear: '1998',
    name: '이소은',
    category: 'girl-solo',
    descNamu: 'https://namu.wiki/w/%EC%9D%B4%EC%86%8C%EC%9D%80(%EA%B0%80%EC%88%98)',
  },
  {
    debutYear: '1998',
    name: '조성모',
    category: 'boy-solo',
    youtubeUrl: 'cYSKoLOFGvQ',
    youtubeStartsAt: 80,
    descNamu: 'https://namu.wiki/w/%EC%A1%B0%EC%84%B1%EB%AA%A8',
  },
  {
    debutYear: '1998',
    name: '최창민',
    category: 'boy-solo',
    descNamu: 'https://namu.wiki/w/%EC%B5%9C%EC%A0%9C%EC%9A%B0(%EB%B0%B0%EC%9A%B0)',
  },
];
