import { IdolCore } from '@/types/idols.d';

export const Y1999: IdolCore[] = [
  // 1999 === === === === ===
  {
    debutYear: '1999',
    name: '강현수',
    category: 'boy-solo',
    descNamu: 'https://namu.wiki/w/V.One',
  },
  {
    debutYear: '1999',
    name: '김범수',
    category: 'boy-solo',
    youtubeUrl: 'hlx3DZQA5PY',
    youtubeStartsAt: 89,
    descNamu: 'https://namu.wiki/w/%EA%B9%80%EB%B2%94%EC%88%98',
  },
  {
    debutYear: '1999',
    name: '두리안',
    category: 'girl-group',
    descNamu: 'https://namu.wiki/w/%EB%91%90%EB%A6%AC%EC%95%88#s-3',
  },
  {
    debutYear: '1999',
    name: '박효신',
    category: 'boy-solo',
    youtubeUrl: 'sr3JaQ3h7YA',
    youtubeStartsAt: 90,
    descNamu: 'https://namu.wiki/w/%EB%B0%95%ED%9A%A8%EC%8B%A0',
  },
  {
    debutYear: '1999',
    name: '백지영',
    category: 'girl-solo',
    youtubeUrl: 'byEZDtOKqoA',
    youtubeStartsAt: 30,
    descNamu: 'https://namu.wiki/w/%EB%B0%B1%EC%A7%80%EC%98%81',
  },
  {
    debutYear: '1999',
    name: '샤니',
    category: 'girl-solo',
    descNamu: 'https://namu.wiki/w/%EC%83%A4%EB%8B%88',
  },
  {
    debutYear: '1999',
    name: '소냐',
    category: 'girl-solo',
    youtubeUrl: 'BAxS5lsyec4',
    youtubeStartsAt: 83,
    descNamu: 'https://namu.wiki/w/%EC%86%8C%EB%83%90(%EA%B0%80%EC%88%98)',
  },
  {
    debutYear: '1999',
    name: '애즈 원',
    category: 'girl-group',
    descNamu: 'https://namu.wiki/w/%EC%95%A0%EC%A6%88%20%EC%9B%90',
  },
  {
    debutYear: '1999',
    name: '야다',
    category: 'boy-group',
    descNamu: 'https://namu.wiki/w/%EC%95%BC%EB%8B%A4(%EB%B0%B4%EB%93%9C)',
  },
  {
    debutYear: '1999',
    name: '유채영',
    category: 'girl-solo',
    descNamu: 'https://namu.wiki/w/%EC%9C%A0%EC%B1%84%EC%98%81',
  },
  {
    debutYear: '1999',
    name: '이수영',
    category: 'girl-solo',
    youtubeUrl: '0fBudhvR1ho',
    youtubeStartsAt: 184,
    descNamu: 'https://namu.wiki/w/%EC%9D%B4%EC%88%98%EC%98%81(%EA%B0%80%EC%88%98)',
  },
  {
    debutYear: '1999',
    name: '이정현',
    category: 'girl-solo',
    youtubeUrl: 'C3OAWCvIzCE',
    youtubeStartsAt: 163,
    descNamu:
      'https://namu.wiki/w/%EC%9D%B4%EC%A0%95%ED%98%84(%EB%A9%80%ED%8B%B0%20%EC%97%94%ED%84%B0%ED%85%8C%EC%9D%B4%EB%84%88)',
  },
  {
    debutYear: '1999',
    name: '채정안',
    category: 'girl-solo',
    youtubeUrl: 'P6UpqC53Pf8',
    youtubeStartsAt: 85,
    descNamu: 'https://namu.wiki/w/%EC%B1%84%EC%A0%95%EC%95%88',
  },
  {
    debutYear: '1999',
    name: '클레오',
    category: 'girl-group',
    descNamu: 'https://namu.wiki/w/%ED%81%B4%EB%A0%88%EC%98%A4',
  },
  {
    debutYear: '1999',
    name: '클릭비',
    category: 'boy-group',
    youtubeUrl: 'mVuZhU5z2AY',
    youtubeStartsAt: 77,
  },
  {
    debutYear: '1999',
    name: '타샤니',
    category: 'girl-group',
    descNamu: 'https://namu.wiki/w/%EC%9C%A4%EB%AF%B8%EB%9E%98',
  },
  {
    debutYear: '1999',
    name: '티티마',
    category: 'girl-group',
    descNamu: 'https://namu.wiki/w/%ED%8B%B0%ED%8B%B0%EB%A7%88(%EA%B1%B8%EA%B7%B8%EB%A3%B9)',
  },
  {
    debutYear: '1999',
    name: '플라워',
    category: 'boy-group',
    descNamu: 'https://namu.wiki/w/%ED%94%8C%EB%9D%BC%EC%9B%8C(%EB%B0%B4%EB%93%9C)',
  },
  {
    debutYear: '1999',
    name: '플라이 투더 스카이',
    category: 'boy-group',
    youtubeUrl: 'tWTq_PMXfBE',
    youtubeStartsAt: 176,
  },
  {
    debutYear: '1999',
    name: '피플크루',
    category: 'boy-group',
  },
  {
    debutYear: '1999',
    name: 'A4',
    category: 'boy-group',
  },
  {
    debutYear: '1999',
    name: 'god',
    category: 'boy-group',
    youtubeUrl: '72BqCAmhnxk',
    youtubeStartsAt: 67,
  },
  {
    debutYear: '1999',
    name: 'O-24',
    category: 'girl-group',
    descNamu: 'https://namu.wiki/w/O-24',
  },
  {
    debutYear: '1999',
    name: 'See U',
    category: 'girl-group',
    descNamu: 'https://namu.wiki/w/See%20U',
  },
  {
    debutYear: '1999',
    name: 'Y2K',
    category: 'boy-group',
    youtubeUrl: 'H5SJfNCf5Ig',
    youtubeStartsAt: 63,
  },
];
