import { IdolCore } from '@/types/idols.d';

export const Y2001: IdolCore[] = [
  // 2001 === === === === ===
  {
    debutYear: '2001',
    name: '더 자두',
    category: 'mixed-group',
    youtubeUrl: 'prTlJcipGbo',
    youtubeStartsAt: 64,
  },
  {
    debutYear: '2001',
    name: '거북이',
    category: 'mixed-group',
    youtubeUrl: 'cNZk2y57jzs',
    youtubeStartsAt: 16,
  },
  {
    debutYear: '2001',
    name: '쥬얼리',
    category: 'girl-group',
    youtubeUrl: 'l9Ih9zqtWJY',
    youtubeStartsAt: 60,
  },
  {
    debutYear: '2001',
    name: '밀크',
    category: 'girl-group',
    youtubeUrl: 'oyJtrvJfvDE',
    youtubeStartsAt: 69,
  },
  {
    debutYear: '2001',
    name: '슈가',
    category: 'girl-group',
    youtubeUrl: 'j6SibyE5PPQ',
    youtubeStartsAt: 77,
  },
  {
    debutYear: '2001',
    name: '투야',
    category: 'girl-group',
  },
  {
    debutYear: '2001',
    name: 'KISS',
    category: 'girl-group',
  },
  {
    debutYear: '2001',
    name: 'S',
    category: 'girl-group',
  },
  {
    debutYear: '2001',
    name: '걸 프렌드',
    category: 'girl-group',
  },
  {
    debutYear: '2001',
    name: '보이스코',
    category: 'girl-group',
  },

  {
    debutYear: '2001',
    name: '에픽하이',
    category: 'boy-group',
    youtubeUrl: 'IAgRgOh_t3o',
    youtubeStartsAt: 16,
  },
  {
    debutYear: '2001',
    name: '브라운 아이즈',
    category: 'boy-group',
    youtubeUrl: 'rZLypVnNhuw',
    youtubeStartsAt: 77,
  },
  {
    debutYear: '2001',
    name: '디베이스',
    category: 'boy-group',
    youtubeUrl: 'Xp17ec9SdXA',
    youtubeStartsAt: 10,
  },
  {
    debutYear: '2001',
    name: 'K-POP',
    category: 'boy-group',
  },
  {
    debutYear: '2001',
    name: '오션',
    category: 'boy-group',
    youtubeUrl: 'jZeOy8GRr7I',
    youtubeStartsAt: 46,
  },
  {
    debutYear: '2001',
    name: 'JTL',
    category: 'boy-group',
    youtubeUrl: 'w-Zu7ZXIKoE',
    youtubeStartsAt: 43,
  },
  {
    debutYear: '2001',
    name: '장나라',
    category: 'girl-solo',
    youtubeUrl: 'fKmU0rmgATE',
    youtubeStartsAt: 0,
  },
  {
    debutYear: '2001',
    name: '하늘',
    category: 'girl-solo',
    youtubeUrl: '0wFngk3YtXw',
    youtubeStartsAt: 27,
  },
  {
    debutYear: '2001',
    name: '죠앤',
    category: 'girl-solo',
    youtubeUrl: 'dxb8kdClnpY',
    youtubeStartsAt: 9,
  },
  {
    debutYear: '2001',
    name: '다나',
    category: 'girl-solo',
    youtubeUrl: 'HdCH3JsW4x8',
    youtubeStartsAt: 83,
  },
  {
    debutYear: '2001',
    name: '유리',
    category: 'girl-solo',
    youtubeUrl: '',
    youtubeStartsAt: 0,
  },
  {
    debutYear: '2001',
    name: '린',
    category: 'girl-solo',
    youtubeUrl: 'nj_6geqNPLA',
    youtubeStartsAt: 58,
  },
  {
    debutYear: '2001',
    name: '페니',
    category: 'girl-solo',
  },
  {
    debutYear: '2001',
    name: '이가희',
    category: 'girl-solo',
  },

  {
    debutYear: '2001',
    name: '성시경',
    category: 'boy-solo',
    youtubeUrl: 'xnH9T6WWznc',
    youtubeStartsAt: 71,
  },
  {
    debutYear: '2001',
    name: '싸이',
    category: 'boy-solo',
    youtubeUrl: 'yqPIEab9-wY',
    youtubeStartsAt: 33,
  },
  {
    debutYear: '2001',
    name: '리치',
    category: 'boy-solo',
    youtubeUrl: 'Nkcomvtw9QY',
    youtubeStartsAt: 72,
  },
  {
    debutYear: '2001',
    name: '문희준',
    category: 'boy-solo',
    youtubeUrl: 'Hen4taZWrdQ',
    youtubeStartsAt: 70,
  },
  {
    debutYear: '2001',
    name: '강성훈',
    category: 'boy-solo',
  },
  {
    debutYear: '2001',
    name: '이재진',
    category: 'boy-solo',
  },
  {
    debutYear: '2001',
    name: '강타',
    category: 'boy-solo',
    youtubeUrl: 'bJQHAv0J2Bs',
    youtubeStartsAt: 203,
  },
  {
    debutYear: '2001',
    name: '론',
    category: 'boy-solo',
  },
];
